apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 1m
  url:  http://pajikos.github.io/home-assistant-helm-chart/
