apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.76
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  values:
    configuration:
      enabled: true
      http:
        use_x_forwarded_for: true
        trusted_proxies:
          - 10.42.0.0/16
    persistence:
      enabled: true
      storageClass: local-path
      size: 10Gi

    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: homeassistant.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tls-homeassistant
          hosts:
            - homeassistant.local
            