apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  values:
    configuration:
      enabled: true
      http:
        use_x_forwarded_for: true
        trusted_proxies:
          - 10.42.0.0/16
    persistence:
      enabled: true
      storageClass: local-path   # k3s default
      size: 10Gi

    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
      - host: homeassistant.local
        paths:
          - path: /
            pathType: ImplementationSpecific

    service:
      type: ClusterIP

    supervisor:
      enabled: true
    tls:
      - secretName: tls-homeassistant
        hosts:
          - homeassistant.local
