apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n

spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: 1.16.20
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system

  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: tls-n8n
          hosts:
            - n8n.local

