apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
  values:
    ingress:
      enabled: true
      hosts:
        - host: n8n.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: tls-n8n
          hosts:
            - n8n.local
    persistence:
      enabled: true
      size: 1Gi
