apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m 
  chart:
    spec:
      chart: rancher
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    replicas: 1
    ingress:
      extraAnnotations:
        kubernetes.io/ingress.class: traefik
      tls:
        source: letsEncrypt      # ← kein "-" davor!
        secretName: rancher-tls  # optional, wenn du einen eigenen Secret-Namen willst
        hosts:
          - rancher.local
