apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 10m 
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
      version: "*"
  values:
    replicas: 1
  ingress:
    extraAnnotations:
      kubernetes.io/ingress.class: traefik
    tls:
      - secretName: rancher-tls
        hosts:
          - rancher.local
