apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m 
  chart:
    spec:
      chart: rancher
      version: "2.1.7"
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    enabled: true
    replicas: 1
    hostname: rancher.local
    ingress:
      enabled: true
      class: "traefik"
      extraAnnotations:
        kubernetes.io/ingress.class: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: rancher.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - source: secret
        - secretName: tls-rancher
