apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-airflow
  namespace: airflow
spec:
  secretName: tls-airflow
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - airflow.local
