apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  timeout: 10m

  chart:
    spec:
      chart: airflow
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system

  values:
    # --------------------
    # Executor
    # --------------------
    executor: LocalExecutor

    # --------------------
    # interne Datenbanken AUS
    # --------------------
    postgresql:
      enabled: false
    mysql:
      enabled: false

    # --------------------
    # Externe DB via ENV (BEST PRACTICE)
    # --------------------
    extraEnv: |
      - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        valueFrom:
          secretKeyRef:
            name: airflow-db
            key: sql_alchemy_conn

    # --------------------
    # Core Components
    # --------------------
    webserver:
      enabled: true

    scheduler:
      enabled: true

    triggerer:
      enabled: true

    # --------------------
    # Persistence
    # --------------------
    dags:
      persistence:
        enabled: true
        size: 1Gi
        accessModes:
          - ReadWriteOnce

    logs:
      persistence:
        enabled: true
        size: 1Gi
        accessModes: 
          - ReadWriteOnce

    # --------------------
    # Ingress (optional)
    # --------------------
    ingress:
      enabled: false
