apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system

  values:
    executor: CeleryExecutor

    # ❌ Postgres aus
    postgresql:
      enabled: false

    # ✅ MySQL Metadata DB
    metadataConnection:
      protocol: mysql
      host: mysql.airflow.svc.cluster.local
      port: 3306
      db: airflow
      user: airflow
      pass: airflow

    # 🔐 Alternativ/zusätzlich per Secret (empfohlen)
    metadataSecretName: airflow-mysql

    images:
      airflow:
        repository: apache/airflow
        tag: "3.0.2"

    webserver:
      enabled: true
      replicas: 1

    scheduler:
      enabled: true
      replicas: 1

    workers:
      replicas: 1

    triggerer:
      enabled: true
      replicas: 1

    migrateDatabaseJob:
      enabled: true