apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: airflow
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system

  values:
    # --------------------
    # Executor
    # --------------------
    executor: LocalExecutor

    # --------------------
    # PostgreSQL AUS
    # --------------------
    postgresql:
      enabled: false

    # --------------------
    # MySQL AUS (extern)
    # --------------------
    mysql:
      enabled: false

    # --------------------
    # Airflow DB Connection (extern)
    # --------------------
    airflow:
      envFrom:
        - secretRef:
            name: airflow-db
      extraPipPackages:
        - pymysql  # für mysql+pymysql

    migrateDatabaseJob:
      enabled: true

    waitForMigrations:
      enabled: false


    # --------------------
    # Core Components
    # --------------------
    webserver:
      enabled: true
    scheduler:
      enabled: true
    triggerer:
      enabled: true

    # --------------------
    # Persistence deaktiviert (da extern)
    # --------------------
    dags:
      persistence:
        enabled: false
    logs:
      persistence:
        enabled: false

    # --------------------
    # Ingress optional
    # --------------------
    ingress:
      enabled: false

    # --------------------
    # Init-Migration (automatisch beim Start)
    # --------------------
    init:
      extraCommand: >
        airflow db upgrade
