apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system

  values:
    executor: CeleryExecutor

    # disable postgres
    postgresql:
      enabled: false

    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    data:
      # need to create airflow-metadata secret first | you can find the template infra/airflow-metadata.yaml
      metadataSecretName: airflow-metadata

    images:
      airflow:
        repository: apache/airflow

    webserver:
      enabled: true
      replicas: 1

    scheduler:
      enabled: true
      replicas: 1

    workers:
      replicas: 1

    triggerer:
      enabled: true
      replicas: 1
    ingress:
      enabled: true
      web:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
        - name: airflow.local
          path: /
          pathType: ImplementationSpecific
        tls:
          enabled: true
          secretName: "tls-airflow"
      flower:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
        - name: airflow.local
        tls:
          enabled: true
          secretName: "tls-airflow"