apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow

spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system

  values:
    executor: KubernetesExecutor

    airflow:
      image:
        repository: apache/airflow
        tag: 2.8.1

    webserver:
      service:
        type: ClusterIP

    scheduler:
      replicas: 1

    triggerer:
      enabled: true

    dags:
      persistence:
        enabled: false
