apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: php-scripts
    files:
      - ../../../airflow-dags/scripts/*.php

generatorOptions:
  disableNameSuffixHash: true